---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: spark
  name: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    name: spark
  name: spark
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'configmaps', 'persistentvolumeclaims']
    verbs: ['get', 'list', 'watch', 'create', 'edit', 'delete', 'deletecollection', 'patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: spark
  name: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: default